platform :ios, '5.0'

pod 'GData', '~> 1.12.0'
pod 'SSPullToRefresh', '~> 1.1.2'
pod 'MBProgressHUD', '~> 0.6'
pod 'QueryManager', '~> 0.0.13'

pod 'SmartNavigationController', '~> 0.0.2'
pod 'UITableViewAtBottomView', '~> 0.0.1'
pod 'UITableViewHeaderFormView', '~> 0.0.1'
pod 'UITableViewHeaderMenuView', '~> 0.0.1'
pod 'UITableViewMaskView', '~> 0.0.1'
pod 'UITableViewSwipeView', '~> 0.0.1'
pod 'ViewHelpers', '~> 0.0.1'
pod 'NSDate-TimeAgo', '~> 0.0.1'