platform :ios, '7.0'

pod 'GData', '~> 1.12.0'
pod 'SSPullToRefresh', '~> 1.1.2'
pod 'MBProgressHUD', '~> 0.6'
pod 'NSDate-TimeAgo', '~> 0.0.1'
pod 'FSMUIViewController', '~> 0.0.10'
pod 'UITableViewHeaderFormView', '~> 0.0.2'
pod 'UITableViewAtBottomView', '~> 0.0.2'
pod 'UITableViewMaskView', '~> 0.0.2'
pod 'UITableViewSwipeView', '~> 0.0.2'
pod 'QueryManager', '~> 0.0.16'
pod 'SmartNavigationController', '~> 0.0.3'
